# Generated by Django 5.2.4 on 2025-11-26 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_message_file_alter_message_text'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='file',
            field=models.TextField(blank=True, null=True, verbose_name='media_file'),
        ),
    ]
