# Generated by Django 5.2.4 on 2025-11-26 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0003_alter_message_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='filenames',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
