# Generated by Django 5.2.4 on 2025-11-26 17:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0004_message_filenames'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='filenames',
        ),
    ]
