# Generated by Django 5.2.4 on 2025-11-26 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0005_remove_message_filenames'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='filenames',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
