# Generated by Django 5.2.4 on 2025-11-26 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0006_message_filenames'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='file',
            field=models.TextField(blank=True, null=True),
        ),
    ]
