# Generated by Django 5.2.4 on 2025-08-05 16:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0005_appointment_cancellation_reason_and_more'),
        ('wallet', '0003_remove_wallettransaction_user_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameField(
            model_name='wallettransaction',
            old_name='reason',
            new_name='description',
        ),
        migrations.AddField(
            model_name='wallettransaction',
            name='appointment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='wallet_transactions', to='appointments.appointment'),
        ),
        migrations.AddField(
            model_name='wallettransaction',
            name='initiated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='initiated_transactions', to=settings.AUTH_USER_MODEL),
        ),
    ]
