# Generated by Django 5.2.4 on 2025-08-01 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0003_appointment_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='psychologistavailability',
            name='locked_until',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
