# Generated by Django 5.2.4 on 2025-08-04 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0004_psychologistavailability_locked_until'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='cancellation_reason',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='appointment',
            name='cancelled_by',
            field=models.CharField(blank=True, choices=[('user', 'User'), ('psychologist', 'Psychologist'), ('', 'None')], default='', max_length=25),
        ),
    ]
