# Generated by Django 5.2.4 on 2025-10-09 09:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0006_payment'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='psychologistavailability',
            options={'ordering': ['date', 'start_time']},
        ),
    ]
