# Generated by Django 5.2.4 on 2026-01-02 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0007_alter_psychologistavailability_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='status',
            field=models.CharField(choices=[('booked', 'Booked'), ('completed', 'Completed'), ('cancelled', 'Cancelled'), ('not_attended', 'Not Attended')], default='booked', max_length=25),
        ),
    ]
