# Generated by Django 5.2.4 on 2026-01-01 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0004_category_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='articleread',
            name='total_reads',
            field=models.PositiveBigIntegerField(default=0),
        ),
    ]
