# Generated by Django 5.2.4 on 2026-01-01 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0005_articleread_total_reads'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='articleread',
            name='total_reads',
        ),
        migrations.AddField(
            model_name='article',
            name='total_reads',
            field=models.PositiveBigIntegerField(default=0),
        ),
    ]
