# Generated by Django 5.2.4 on 2025-12-18 06:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0008_message_is_read'),
        ('notification', '0002_alter_notification_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='related_room',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='chat_notifications', to='chat.chatroom'),
        ),
        migrations.AddField(
            model_name='notification',
            name='un_read_count',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
