# Generated by Django 5.2.4 on 2025-12-18 08:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notification', '0003_notification_related_room_notification_un_read_count'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notification',
            name='related_room',
        ),
        migrations.RemoveField(
            model_name='notification',
            name='un_read_count',
        ),
    ]
