# Generated by Django 5.2.4 on 2026-01-10 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notification', '0005_alter_notification_notification_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='conversation_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
