# Generated by Django 5.2.4 on 2025-09-12 07:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('prescription', '0002_healthtracking'),
    ]

    operations = [
        migrations.RenameField(
            model_name='healthtracking',
            old_name='EmotionalState',
            new_name='emotionalstate',
        ),
    ]
