# Generated by Django 5.2.4 on 2025-07-21 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication_app', '0002_alter_customuser_options_customuser_date_joined_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='emailotp',
            name='purpose',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
