# Generated by Django 5.2.4 on 2025-07-22 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication_app', '0003_emailotp_purpose'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('user', 'User'), ('psychologist', 'Psychologist'), ('admin', 'Admin')], max_length=20),
        ),
    ]
