# Generated by Django 5.2.4 on 2025-09-26 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication_app', '0004_alter_customuser_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='psychologistprofile',
            name='is_submitted',
            field=models.BooleanField(default=False),
        ),
    ]
