# Generated by Django 5.2.4 on 2025-09-26 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication_app', '0005_psychologistprofile_is_submitted'),
    ]

    operations = [
        migrations.AddField(
            model_name='psychologistprofile',
            name='rejection_reason',
            field=models.TextField(blank=True, null=True),
        ),
    ]
