# Generated by Django 5.2.4 on 2025-10-14 04:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication_app', '0006_psychologistprofile_rejection_reason'),
    ]

    operations = [
        migrations.AddField(
            model_name='psychologistprofile',
            name='bank_account_no',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='psychologistprofile',
            name='ifsc_code',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
